# Site settings ...
uri: hoony.de
url: http://hoony.de
name: Hoony Chang
title: website de hoony
email: hoonch3@gmail.com
author: hoony
baseurl: ""
keywords: "civic hacker, javascript, node, basketball"
description: "Hi, I'm hoony, civic hacker in Korea. quite enthusiastic at civic hacking, javascript, and basketball."
social_username: hoonch3

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
# paginate_path: "/blog/page:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
