# Site settings ...
uri: the6thm0nth.github.io
url: http://the6thm0nth.github.io
name: Hoony Chang
title: "Hoony's home, sweet home"
email: the6thm0nth@outlook.com
author: hoony
baseurl: ""
keywords: "civic hacker, javascript, node, basketball"
description: "<b>&lt;me</b> <b>type</b>='civic hacker' <b>language</b>='node.js, react.js' <b>enjoy</b>='coding, moving, reading, basketball' <b>/&gt;</b>"
social_username: the6thm0nth

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:categories/:title
# paginate_path: "/blog/page:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
